const products =[
    {
        id:0,
        nome:"sei la",
        preco: 2,
        descricao:"Fonte Corsair 750W",
        img:"./imagem/corsair750.png",
    },
    {
        id:1,
        nome:"sei la",
        preco: 2,
        descricao:"Fonte DeepCool 700W",
        img:"./imagem/deepcool700.png",
    },
    {
        id:2,
        nome:"Gabinete Cyclon",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/gabinete_cylon.jpg",
    },
    {
        id:3,
        nome:"Gabinete Sharkoon",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/gabinete_sharkoon.jpg",
    },
    {
        id:4,
        nome:"Placa De Video GTX1650",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/gtx1650.jpg",
    },
    {
        id:5,
        nome:"Processador i310",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/i310.png",
    },
    {
        id:6,
        nome:"Placa mãe Asus",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/placaasus.png",
    },
    {
        id:7,
        nome:"Placa mãe Gigabyte",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/placagigabyte.png",
    },
    {
        id:8,
        nome:"Processador Ryzen 5 3600",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/r53600.png",
    },
    {
        id:9,
        nome:"Memória RAM Ballistic",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/ramballistic.png",
    },
    {
        id:10,
        nome:"Memória RAM HyperX",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/ramhyperx.png",
    },
    {
        id:11,
        nome:"Placa de Video RX 580",
        preco: 2,
        descricao:"piriri pororo",
        img:"./imagem/rx580.jpg",
    },
    ];